/**
 * Dev seed — creates 10 sample properties linked to the test landlord.
 * Run with:  npx ts-node src/database/seeds/dev-properties.ts
 *
 * Requires dev-users.ts to have been run first.
 */

import { pool } from '../../config/database';

const UNSPLASH = (id: string, w = 800, h = 600) =>
  `https://images.unsplash.com/photo-${id}?w=${w}&h=${h}&fit=crop&auto=format`;

const properties = [
  {
    listing_type: 'standard',
    property_type: 'apartment',
    title: '2-Bedroom Serviced Apartment in Lekki Phase 1',
    description:
      'Tastefully finished 2-bedroom apartment in the heart of Lekki Phase 1. The apartment features modern fittings, 24/7 power supply via solar inverter, and ample parking space. Ideal for young professionals.',
    address: '14B Admiralty Way, Lekki Phase 1',
    lga: 'Eti-Osa',
    state: 'Lagos',
    latitude: 6.4281,
    longitude: 3.4219,
    nearest_landmark: 'Lekki Conservation Centre',
    bedrooms: 2,
    bathrooms: 2,
    amenities: ['Parking', '24/7 Power', 'Security', 'Water Supply', 'Internet', 'Air Conditioning'],
    monthly_rent: 180000,
    yearly_rent: 1800000,
    caution_fee: 180000,
    agency_fee: 180000,
    tenancy_mode: 'both',
    available_units: 3,
    is_available: true,
    approval_status: 'approved',
    photos: [
      UNSPLASH('1545324418-cc1a3fa10c00'),
      UNSPLASH('1560448204-e02f11c3d0e2'),
      UNSPLASH('1502672260266-1c1ef2d93688'),
    ],
    rules: 'No pets. No loud music after 10 PM. No subletting.',
    max_occupants: 4,
    gender_preference: 'any',
  },
  {
    listing_type: 'standard',
    property_type: 'duplex',
    title: '4-Bedroom Duplex in Victoria Island',
    description:
      'Luxurious 4-bedroom duplex on a quiet street in Victoria Island. Features a private swimming pool, fitted kitchen, boys quarter, and 3-car garage. Perfect for executives and diplomats.',
    address: '7 Adeola Odeku Street, Victoria Island',
    lga: 'Eti-Osa',
    state: 'Lagos',
    latitude: 6.4281,
    longitude: 3.4219,
    nearest_landmark: 'Eko Hotel & Suites',
    bedrooms: 4,
    bathrooms: 4,
    amenities: ['Swimming Pool', 'Gym', 'Parking', '24/7 Power', 'Security', 'Water Supply', 'Boys Quarter', 'Internet'],
    monthly_rent: null,
    yearly_rent: 9000000,
    caution_fee: 1000000,
    agency_fee: 900000,
    tenancy_mode: 'yearly',
    available_units: 1,
    is_available: true,
    approval_status: 'approved',
    photos: [
      UNSPLASH('1613977257363-707ba9348227'),
      UNSPLASH('1512917774080-9991f1c4c750'),
      UNSPLASH('1600596542815-ffad4c1539a9'),
    ],
    rules: 'No parties. No subletting. Tenant responsible for lawn maintenance.',
    max_occupants: 8,
    gender_preference: 'any',
  },
  {
    listing_type: 'standard',
    property_type: 'flat',
    title: '3-Bedroom Flat in Surulere',
    description:
      'Spacious 3-bedroom flat on the 2nd floor of a 4-storey building in Surulere. Close to National Stadium, market, and major bus stops. Good water supply and reliable power from estate transformer.',
    address: '22 Adeniran Ogunsanya Street, Surulere',
    lga: 'Surulere',
    state: 'Lagos',
    latitude: 6.5059,
    longitude: 3.3569,
    nearest_landmark: 'National Stadium',
    bedrooms: 3,
    bathrooms: 2,
    amenities: ['Parking', 'Water Supply', 'Security', 'Balcony'],
    monthly_rent: null,
    yearly_rent: 900000,
    caution_fee: 150000,
    agency_fee: 90000,
    tenancy_mode: 'yearly',
    available_units: 1,
    is_available: true,
    approval_status: 'approved',
    photos: [
      UNSPLASH('1567684014761-b65e2e3b4b1e'),
      UNSPLASH('1556909114-f6e7ad7d3136'),
      UNSPLASH('1484154218962-a197022b5858'),
    ],
    rules: 'No business activities. No pet animals. Quiet hours from 11 PM.',
    max_occupants: 6,
    gender_preference: 'any',
  },
  {
    listing_type: 'standard',
    property_type: 'self_contain',
    title: 'Self-Contain in Yaba',
    description:
      'Cosy self-contained apartment with modern tiles, fitted wardrobe, and private bathroom. Located in a serene compound with 24/7 security. Close to UNILAG and tech hubs.',
    address: '5 Herbert Macaulay Way, Yaba',
    lga: 'Lagos Mainland',
    state: 'Lagos',
    latitude: 6.5085,
    longitude: 3.3771,
    nearest_landmark: 'University of Lagos (UNILAG)',
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['Water Supply', 'Security', 'Air Conditioning', 'Internet'],
    monthly_rent: 55000,
    yearly_rent: 600000,
    caution_fee: 55000,
    agency_fee: 60000,
    tenancy_mode: 'both',
    available_units: 2,
    is_available: true,
    approval_status: 'approved',
    photos: [
      UNSPLASH('1522708323590-d24dbb6b0267'),
      UNSPLASH('1493809842364-78817add7ffb'),
      UNSPLASH('1540518614846-7eded433c457'),
    ],
    rules: 'No cooking in the room. Quiet after 10 PM.',
    max_occupants: 2,
    gender_preference: 'any',
  },
  {
    listing_type: 'standard',
    property_type: 'bungalow',
    title: '3-Bedroom Bungalow in Ikorodu',
    description:
      'Well-maintained 3-bedroom bungalow with a large compound, garden, and external boys quarter. Situated in a peaceful neighborhood in Ikorodu. Good for families.',
    address: '10 Oba Sekumade Road, Ikorodu',
    lga: 'Ikorodu',
    state: 'Lagos',
    latitude: 6.6194,
    longitude: 3.5064,
    nearest_landmark: 'Ikorodu General Hospital',
    bedrooms: 3,
    bathrooms: 2,
    amenities: ['Parking', 'Garden', 'Boys Quarter', 'Water Supply', 'Security'],
    monthly_rent: null,
    yearly_rent: 600000,
    caution_fee: 100000,
    agency_fee: 60000,
    tenancy_mode: 'yearly',
    available_units: 1,
    is_available: true,
    approval_status: 'approved',
    photos: [
      UNSPLASH('1583608205776-bfd35f0d9f83'),
      UNSPLASH('1558618666-fcd25c85cd64'),
      UNSPLASH('1570129477492-45c003edd2be'),
    ],
    rules: 'Tenants maintain the garden. No commercial activities.',
    max_occupants: 7,
    gender_preference: 'any',
  },
  {
    listing_type: 'standard',
    property_type: 'apartment',
    title: '2-Bedroom Apartment in Ajah',
    description:
      'Newly built 2-bedroom apartment in a gated estate in Ajah. Features POP ceiling, modern kitchen, and dedicated parking. Close to Ajah market and Abraham Adesanya roundabout.',
    address: '3 Orchid Road, Lafiaji, Ajah',
    lga: 'Eti-Osa',
    state: 'Lagos',
    latitude: 6.4698,
    longitude: 3.5661,
    nearest_landmark: 'Abraham Adesanya Roundabout',
    bedrooms: 2,
    bathrooms: 2,
    amenities: ['Parking', 'Security', 'Water Supply', 'Air Conditioning', 'CCTV'],
    monthly_rent: 120000,
    yearly_rent: 1200000,
    caution_fee: 120000,
    agency_fee: 120000,
    tenancy_mode: 'both',
    available_units: 4,
    is_available: true,
    approval_status: 'approved',
    photos: [
      UNSPLASH('1600607687939-ce8a6c25118c'),
      UNSPLASH('1600566753190-17f0baa2a6c3'),
      UNSPLASH('1600573472592-401b489a3cdc'),
    ],
    rules: 'No parties. Waste must be properly disposed. No pets.',
    max_occupants: 4,
    gender_preference: 'any',
  },
  {
    listing_type: 'standard',
    property_type: 'flat',
    title: '2-Bedroom Flat in Maryland',
    description:
      'Bright and airy 2-bedroom flat in a well-maintained block in Maryland. Close to Maryland Mall, bus stops, and major expressways. Reliable electricity and borehole water supply.',
    address: '18 Ikorodu Road, Maryland',
    lga: 'Kosofe',
    state: 'Lagos',
    latitude: 6.5696,
    longitude: 3.3647,
    nearest_landmark: 'Maryland Mall',
    bedrooms: 2,
    bathrooms: 1,
    amenities: ['Parking', 'Security', 'Water Supply', 'Balcony'],
    monthly_rent: null,
    yearly_rent: 750000,
    caution_fee: 75000,
    agency_fee: 75000,
    tenancy_mode: 'yearly',
    available_units: 2,
    is_available: true,
    approval_status: 'approved',
    photos: [
      UNSPLASH('1560185007-cde9b389e3f6'),
      UNSPLASH('1565182999561-18d7dc61c393'),
      UNSPLASH('1564078516393-cf04bd966897'),
    ],
    rules: 'No subletting. Tenant covers waste disposal bills.',
    max_occupants: 4,
    gender_preference: 'any',
  },
  {
    listing_type: 'student',
    property_type: 'hostel',
    title: 'Student Hostel Room Near UNILAG, Akoka',
    description:
      'Clean and secure hostel room for 2 students near UNILAG main gate. Room includes bunk beds, wardrobe, study desk, and shared bathroom. Constant water supply and stable electricity.',
    address: '9 Jibowu Street, Akoka, Yaba',
    lga: 'Lagos Mainland',
    state: 'Lagos',
    latitude: 6.5227,
    longitude: 3.3724,
    nearest_landmark: 'UNILAG Main Gate',
    nearest_university: 'University of Lagos (UNILAG)',
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['Water Supply', 'Security', 'Study Area', 'Laundry'],
    monthly_rent: 25000,
    yearly_rent: 280000,
    caution_fee: 25000,
    agency_fee: 0,
    tenancy_mode: 'both',
    available_units: 5,
    is_available: true,
    approval_status: 'approved',
    photos: [
      UNSPLASH('1555854877-bab93f6ca09b'),
      UNSPLASH('1631049307264-da0ec9d70304'),
      UNSPLASH('1524758631624-e2822e304c36'),
    ],
    rules: 'Lights out by midnight. No visitors after 10 PM. No cooking in rooms.',
    max_occupants: 2,
    gender_preference: 'any',
  },
  {
    listing_type: 'student',
    property_type: 'bedspace',
    title: 'Affordable Bedspace for Female Students, Bariga',
    description:
      'Shared room bedspace for female students in a safe, well-managed hostel in Bariga. Close to UNILAG and Yabatech. Room accommodates 4 occupants with individual lockers and reading lamps.',
    address: '15 Shipeolu Street, Bariga',
    lga: 'Shomolu',
    state: 'Lagos',
    latitude: 6.5378,
    longitude: 3.3803,
    nearest_landmark: 'Bariga Market',
    nearest_university: 'Yaba College of Technology (Yabatech)',
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['Water Supply', 'Security', 'Locker', 'Study Lamp', 'Laundry'],
    monthly_rent: 15000,
    yearly_rent: 160000,
    caution_fee: 15000,
    agency_fee: 0,
    tenancy_mode: 'both',
    available_units: 4,
    is_available: true,
    approval_status: 'approved',
    photos: [
      UNSPLASH('1631049552240-59c37f38802b'),
      UNSPLASH('1555854877-bab93f6ca09b'),
      UNSPLASH('1586023492125-27b2c045efd7'),
    ],
    rules: 'Female occupants only. No male visitors in rooms. Lights out by 11 PM.',
    max_occupants: 4,
    gender_preference: 'female',
  },
  {
    listing_type: 'standard',
    property_type: 'house',
    title: '5-Bedroom Detached House in Magodo',
    description:
      'Exquisite 5-bedroom detached house in the prestigious Magodo Phase 2 estate. Features a spacious living room, fully fitted kitchen, family lounge, 2 boys quarters, and a 4-car garage. Located in a serene and well-secured estate.',
    address: '4 Shangisha Road, Magodo Phase 2',
    lga: 'Kosofe',
    state: 'Lagos',
    latitude: 6.6020,
    longitude: 3.3760,
    nearest_landmark: 'Magodo Phase 2 Estate Gate',
    bedrooms: 5,
    bathrooms: 5,
    amenities: ['Parking', 'Boys Quarter', '24/7 Power', 'Security', 'Water Supply', 'CCTV', 'Garden', 'Internet'],
    monthly_rent: null,
    yearly_rent: 12000000,
    caution_fee: 1200000,
    agency_fee: 1200000,
    tenancy_mode: 'yearly',
    available_units: 1,
    is_available: true,
    approval_status: 'approved',
    photos: [
      UNSPLASH('1600047509807-ba8f99d2cdde'),
      UNSPLASH('1600596542815-ffad4c1539a9'),
      UNSPLASH('1600607687939-ce8a6c25118c'),
      UNSPLASH('1613977257363-707ba9348227'),
    ],
    rules: 'No commercial use. Estate rules apply. Tenant must register vehicles with estate management.',
    max_occupants: 12,
    gender_preference: 'any',
  },
];

async function seed() {
  const landlordResult = await pool.query(
    `SELECT id FROM users WHERE phone_number = '+2348100000002' AND role = 'landlord' LIMIT 1`
  );

  if (landlordResult.rows.length === 0) {
    console.error('Landlord user not found. Run dev-users.ts seed first.');
    process.exit(1);
  }

  const landlordId = landlordResult.rows[0].id;

  for (const p of properties) {
    await pool.query(
      `INSERT INTO properties (
        landlord_id, listing_type, property_type, title, description, address,
        lga, state, latitude, longitude, nearest_landmark, nearest_university,
        bedrooms, bathrooms, amenities, monthly_rent, yearly_rent, caution_fee,
        agency_fee, tenancy_mode, available_units, is_available, approval_status,
        photos, rules, max_occupants, gender_preference
      ) VALUES (
        $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27
      )
      ON CONFLICT DO NOTHING`,
      [
        landlordId,
        p.listing_type,
        p.property_type,
        p.title,
        p.description,
        p.address,
        p.lga,
        p.state,
        p.latitude,
        p.longitude,
        p.nearest_landmark,
        (p as any).nearest_university ?? null,
        p.bedrooms,
        p.bathrooms,
        JSON.stringify(p.amenities),
        p.monthly_rent ?? null,
        p.yearly_rent ?? null,
        p.caution_fee,
        p.agency_fee,
        p.tenancy_mode,
        p.available_units,
        p.is_available,
        p.approval_status,
        JSON.stringify(p.photos),
        p.rules,
        p.max_occupants,
        p.gender_preference,
      ]
    );
    console.log(`✓ seeded — ${p.title}`);
  }

  await pool.end();
  console.log('\nDone. 10 properties seeded.');
}

seed().catch(err => {
  console.error(err);
  process.exit(1);
});
